"""Render SOP-REPORT.md from a run directory's results.json + meta.json.

Rendering is separate from measuring so `python -m sop report` can rebuild the
report from stored data. A SOP with no stored result is shown as 'not run' and
SOP 5 is always shown as deferred: the report never implies a number it does
not have.
"""
from __future__ import annotations

from .runlog import RunContext

SOP_QUESTIONS = {
    "SOP1": "Impact of binary delta differencing on the firmware payload footprint and on network "
            "bandwidth saturation for constrained Class 2 devices.",
    "SOP2": "Computational memory overhead and transmission latency of OSCORE compared with standard "
            "cryptographic handshakes in constrained networks.",
    "SOP3": "Deterministic reliability of ledger-anchored smart contracts for cryptographic authenticity "
            "and absolute payload revocation.",
    "SOP4": "Efficiency of offloading Web3 logic to the Edge Gateway: preserving the target node's SRAM "
            "and processing cycles.",
    "SOP5": "Systemic performance of the full Ledger-Anchored Delta-OTA architecture across continuous "
            "hardware metrics under automated multi-cycle testing.",
}

DEFERRED_SOP5 = (
    "Deferred. The 60-cycle automated campaign is run after the tool is approved for implementation. "
    "The runner already provides what it needs: host-timestamped serial capture and parsing (`[Metrics]`, "
    "`[MEM]`, `[Success] Block`), the statistics module (mean, SD, p95, 95% CI), the gateway status feed "
    "with event timestamps, and the chain driver."
)

STATUS_LABEL = {
    "ok": "ok",
    "skipped": "SKIPPED",
    "failed": "FAILED",
    "not-implemented": "not implemented yet",
}


def _esc(v) -> str:
    return str(v).replace("|", "\\|").replace("\n", " ")


def _table(t: dict) -> str:
    head = "| " + " | ".join(_esc(c) for c in t["columns"]) + " |"
    sep = "|" + "|".join("---" for _ in t["columns"]) + "|"
    body = ["| " + " | ".join(_esc(c) for c in row) + " |" for row in t["rows"]]
    out = [f"**{t['caption']}** _({t['kind']})_", "", head, sep, *body]
    if t.get("note"):
        out += ["", f"_{t['note']}_"]
    return "\n".join(out)


def render(ctx: RunContext) -> str:
    meta, results = ctx.meta, ctx.results
    lines = [
        "# SOP Evidence Report",
        "",
        "Generated by `python -m sop`. Every number is tagged **measured** (taken on this machine/device), "
        "**modelled** (computed from stated assumptions) or **cited** (from the literature).",
        "",
        "## Run",
        "",
        f"- Started (UTC): {meta.get('started_utc')}",
        f"- Commit: `{meta.get('git_commit')}`{' (working tree has uncommitted changes)' if meta.get('git_dirty') else ''}",
        f"- Host: {meta.get('platform')}, {meta.get('cpu_count')} CPUs; Python {meta.get('python')}",
        f"- Packages: " + ", ".join(f"{k} {v}" for k, v in (meta.get("packages") or {}).items()),
        f"- OSCORE mode under test: `{meta.get('oscore_mode')}`",
    ]
    for i in meta.get("inputs", []):
        lines.append(f"- Input **{i['label']}**: `{i['path']}` ({i['bytes']:,} B, sha256 `{i['sha256'][:16]}…`)")
    lines.append("")

    env = results.get("ENV")
    if env:
        lines += _section(env, heading="Environment", question=None)

    for sop in ("SOP1", "SOP2", "SOP3", "SOP4"):
        r = results.get(sop)
        if r:
            lines += _section(r, heading=f"{sop} - {r['title']}", question=SOP_QUESTIONS[sop])
        else:
            lines += [f"## {sop}", "", f"> {SOP_QUESTIONS[sop]}", "", "_Not run in this session._", ""]

    lines += ["## SOP5", "", f"> {SOP_QUESTIONS['SOP5']}", "", DEFERRED_SOP5, ""]
    return "\n".join(lines).rstrip() + "\n"


def _section(r: dict, heading: str, question: str | None) -> list[str]:
    out = [f"## {heading}", ""]
    if question:
        out += [f"> {question}", ""]
    tag = f"`{r['mode']}`"
    status = STATUS_LABEL.get(r["status"], r["status"])
    out.append(f"Status: **{status}** ({tag})" + (f" - {r['reason']}" if r.get("reason") else ""))
    out.append("")
    if r["claims"]:
        out += ["**Claims (ready to cite):**", ""]
        out += [f"- {c}" for c in r["claims"]]
        out.append("")
    for t in r["tables"]:
        out += [_table(t), ""]
    if r["notes"]:
        out += ["**Notes:**", ""]
        out += [f"- {n}" for n in r["notes"]]
        out.append("")
    if r["files"]:
        out += ["Raw data: " + ", ".join(f"`{f}`" for f in r["files"]), ""]
    return out


def write_report(ctx: RunContext) -> str:
    text = render(ctx)
    (ctx.dir / "SOP-REPORT.md").write_text(text, encoding="utf-8")
    return str(ctx.dir / "SOP-REPORT.md")
